
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 1800000 #1800000 == 30 min, #60000 = 1 min for debugging expired JWT's